---
inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7

Naming/MethodParameterName:
  AllowedNames: ['op', 'kv', 'k', 'id']
RSpec/MultipleExpectations:
  Max: 3
